import { useMemo, useState, type ReactNode } from 'react';
import { QueryClient, QueryClientProvider, useQueryClient } from '@tanstack/react-query';
import { Link, Route, Switch, useLocation, Router as WouterRouter } from 'wouter';
import {
  Activity, Archive, ArrowUpRight, Bell, Bot, Boxes, Check, ChevronRight, CircleHelp,
  ClipboardList, Clock3, Code2, Database, FileText, Gauge, HeartPulse, LayoutDashboard,
  Megaphone, Menu, MoreHorizontal, PackageCheck, Pencil, Plus, Radio, RefreshCw,
  RotateCcw, Search, Send, Settings2, ShieldCheck, Trash2,
  UserRound, UsersRound, X, Zap,
} from 'lucide-react';
import {
  getGetContentQueryKey, getGetRewardStockQueryKey, getGetSettingsQueryKey,
  getGetUserQueryKey, getHealthCheckQueryKey, getListAuditLogsQueryKey, getListBroadcastsQueryKey,
  getListChannelsQueryKey, getListDeliveriesQueryKey, getListMilestonesQueryKey, getListRewardsQueryKey,
  getListUsersQueryKey, useApplyUserAction, useCreateBroadcast, useCreateChannel, useCreateMilestone,
  useCreateReward, useDeleteChannel, useDeleteMilestone, useDeleteReward, useGetContent, useGetDashboard,
  useGetRewardStock, useGetSettings, useGetUser, useHealthCheck, useListAuditLogs, useListBroadcasts,
  useListChannels, useListDeliveries, useListMilestones, useListRewards, useListUsers, useUpdateChannel,
  useUpdateContent, useUpdateMilestone, useUpdateReward, useUpdateSettings,
  type Broadcast, type BotContent, type BotSettings, type ForceChannel, type Milestone, type Reward,
  type StockSummary, type User,
} from '@workspace/api-client-react';
import { ErrorBoundary } from '@/components/error-boundary';
import NotFound from '@/pages/not-found';
import './index.css';

const queryClient = new QueryClient();

const navGroups = [
  { label: 'Command', items: [{ href: '/', label: 'Overview', icon: LayoutDashboard }, { href: '/rewards', label: 'Rewards', icon: PackageCheck }, { href: '/users', label: 'Users', icon: UsersRound }] },
  { label: 'Operations', items: [{ href: '/channels', label: 'Channels', icon: Radio }, { href: '/content', label: 'Bot content', icon: FileText }, { href: '/broadcasts', label: 'Broadcasts', icon: Megaphone }] },
  { label: 'Governance', items: [{ href: '/audit', label: 'Audit log', icon: ClipboardList }, { href: '/settings', label: 'Settings', icon: Settings2 }] },
];

const pageMeta: Record<string, { eyebrow: string; title: string; description: string }> = {
  '/': { eyebrow: 'Command room', title: 'Good morning, operator.', description: 'Your bot’s health, reward runway, and referral pulse in one calm view.' },
  '/rewards': { eyebrow: 'Inventory control', title: 'Rewards', description: 'Keep every milestone funded before your community gets there.' },
  '/users': { eyebrow: 'Member operations', title: 'Users', description: 'Search, inspect, and make precise adjustments to Telegram members.' },
  '/channels': { eyebrow: 'Access control', title: 'Force-subscribe channels', description: 'Shape the entry path without making it feel like a gate.' },
  '/content': { eyebrow: 'Bot voice', title: 'Content', description: 'Edit the words your bot uses at the moments that matter.' },
  '/broadcasts': { eyebrow: 'Outbound', title: 'Broadcasts', description: 'Queue announcements and watch delivery settle.' },
  '/audit': { eyebrow: 'Governance', title: 'Audit log', description: 'A quiet record of every operator action.' },
  '/settings': { eyebrow: 'System posture', title: 'Settings', description: 'Tune referral access, maintenance mode, and support behavior.' },
};

function cn(...values: Array<string | false | null | undefined>) { return values.filter(Boolean).join(' '); }
function prettyDate(value?: string | null) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }); }
function prettyTime(value?: string | null) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? value : d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); }
function number(value?: number | null) { return new Intl.NumberFormat('en-US').format(value ?? 0); }
function initials(value?: string | null) { return (value || 'OP').replace('@', '').slice(0, 2).toUpperCase(); }

function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'cyan' | 'green' | 'amber' | 'red' | 'navy' }) {
  return <span className={cn('badge', `badge-${tone}`)}>{children}</span>;
}

function Button({ children, variant = 'primary', className, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'quiet' | 'danger' | 'outline' }) {
  return <button className={cn('btn', `btn-${variant}`, className)} {...props}>{children}</button>;
}

function Card({ children, className = '', title, action }: { children: ReactNode; className?: string; title?: string; action?: ReactNode }) {
  return <section className={cn('panel', className)}>{title || action ? <div className="panel-head"><div>{title && <h2 className="section-title">{title}</h2>}</div>{action}</div> : null}{children}</section>;
}

function EmptyState({ icon: Icon = Boxes, title, detail, action }: { icon?: typeof Boxes; title: string; detail: string; action?: ReactNode }) {
  return <div className="empty-state"><div className="empty-icon"><Icon size={20} /></div><strong>{title}</strong><p>{detail}</p>{action}</div>;
}

function ErrorState({ retry }: { retry?: () => void }) {
  return <div className="state-box error-state"><ShieldCheck size={18} /><div><strong>Couldn’t load this surface</strong><p>The API did not respond. Your changes are safe.</p></div>{retry && <Button variant="outline" onClick={retry}>Retry</Button>}</div>;
}

function LoadingRows({ count = 4 }: { count?: number }) {
  return <div className="loading-stack">{Array.from({ length: count }).map((_, i) => <div className="skeleton-row" key={i}><span /><span /><span /></div>)}</div>;
}

function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (value: boolean) => void; label?: string }) {
  return <button type="button" aria-label={label || 'Toggle setting'} data-testid={`toggle-${label || 'setting'}`} className={cn('toggle', checked && 'toggle-on')} onClick={() => onChange(!checked)}><span /></button>;
}

function Modal({ title, onClose, children, wide = false }: { title: string; onClose: () => void; children: ReactNode; wide?: boolean }) {
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className={cn('modal', wide && 'modal-wide')}><div className="modal-head"><div><div className="eyebrow">Operator action</div><h2>{title}</h2></div><button className="icon-btn" aria-label="Close dialog" data-testid="button-close-dialog" onClick={onClose}><X size={18} /></button></div>{children}</div></div>;
}

function Shell({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const health = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey(), refetchInterval: 30000 } });
  const current = pageMeta[location] || pageMeta['/'];
  return <div className="app-shell">
    <aside className={cn('sidebar', mobileOpen && 'sidebar-open')}>
      <div className="brand"><div className="brand-mark"><Bot size={20} /></div><div><strong>Relayroom</strong><span>refer & reward ops</span></div></div>
      <div className="workspace-switch"><span className="bot-avatar">R</span><div><small>Workspace</small><strong>Relayroom Bot</strong></div><ChevronRight size={15} /></div>
      <nav className="side-nav">{navGroups.map(group => <div className="nav-group" key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(item => { const Icon = item.icon; return <Link key={item.href} href={item.href} data-testid={`link-${item.label.toLowerCase().replaceAll(' ', '-')}`} className={cn('nav-item', location === item.href && 'nav-item-active')} onClick={() => setMobileOpen(false)}><Icon size={17} /><span>{item.label}</span>{item.href === '/rewards' && <span className="nav-pulse" />}</Link>; })}</div>)}</nav>
      <div className="side-bottom"><div className="health-mini"><span className={cn('health-dot', health.isError ? 'health-bad' : 'health-good')} /><div><small>Bot heartbeat</small><strong>{health.isLoading ? 'Checking…' : health.isError ? 'Needs attention' : 'Operational'}</strong></div></div><div className="operator"><span className="operator-avatar">O</span><div><strong>Owner</strong><small>Telegram admin</small></div><MoreHorizontal size={17} /></div></div>
    </aside>
    {mobileOpen && <button className="mobile-scrim" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}
    <main className="main-shell">
      <header className="topbar"><button className="mobile-menu icon-btn" aria-label="Open navigation" data-testid="button-open-navigation" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><div className="crumb"><span>Relayroom</span><ChevronRight size={13} /><strong>{current.title}</strong></div><div className="top-actions"><div className="live-status"><span className={cn('health-dot', health.isError ? 'health-bad' : 'health-good')} />{health.isError ? 'API offline' : 'All systems nominal'}</div><button className="icon-btn notification-btn" aria-label="Notifications" data-testid="button-notifications"><Bell size={18} /><span /></button><div className="top-avatar">O</div></div></header>
      <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">{current.eyebrow}</div><h1>{current.title}</h1><p>{current.description}</p></div><div className="heading-meta"><span className="mono">UTC {prettyTime(new Date().toISOString())}</span><span className="sync-mark"><RefreshCw size={13} /> live sync</span></div></div>{children}</div>
    </main>
  </div>;
}

function DashboardPage() {
  const dashboard = useGetDashboard();
  const stock = useGetRewardStock();
  const metrics = dashboard.data?.metrics;
  const cards = [
    { label: 'Total users', value: number(metrics?.totalUsers), delta: '+8.4%', icon: UsersRound, tone: 'cyan' },
    { label: 'Verified users', value: number(metrics?.verifiedUsers), delta: 'of total', icon: ShieldCheck, tone: 'green' },
    { label: 'Successful referrals', value: number(metrics?.successfulReferrals), delta: '+12 this week', icon: ArrowUpRight, tone: 'amber' },
    { label: 'Rewards delivered', value: number(metrics?.rewardsDelivered), delta: `${number(metrics?.failedDeliveries)} failed`, icon: PackageCheck, tone: 'coral' },
  ];
  return <div className="animate-rise">
    <div className="metric-grid">{cards.map(({ label, value, delta, icon: Icon, tone }) => <Card key={label} className="metric-card"><div className={cn('metric-icon', `metric-${tone}`)}><Icon size={18} /></div><div className="metric-label">{label}</div><div className="metric-value" data-testid={`metric-${label.toLowerCase().replaceAll(' ', '-')}`}>{dashboard.isLoading ? '—' : value}</div><div className="metric-delta">{delta}</div></Card>)}</div>
    <div className="dashboard-grid">
      <Card title="Reward runway" action={<Link href="/rewards" className="text-link" data-testid="link-view-inventory">View inventory <ArrowUpRight size={14} /></Link>}>
        {stock.isLoading ? <LoadingRows count={3} /> : stock.isError ? <ErrorState retry={() => stock.refetch()} /> : <StockBars stock={stock.data || []} />}
      </Card>
      <Card title="Bot posture" className="posture-card"><div className="posture-score"><div className="score-ring"><span>{dashboard.isError ? '—' : '92'}</span><small>/100</small></div><div><strong>Steady and ready</strong><p>No operational blockers detected in the last hour.</p></div></div><div className="posture-list"><div><span className="posture-dot green" />Referral flow <b>Nominal</b></div><div><span className="posture-dot cyan" />Delivery queue <b>Clear</b></div><div><span className="posture-dot amber" />Inventory watch <b>{(stock.data || []).some(s => s.available < 5) ? 'Review' : 'Healthy'}</b></div></div></Card>
    </div>
    <Card title="Recent activity" action={<Link href="/audit" className="text-link" data-testid="link-open-audit">Open audit log <ArrowUpRight size={14} /></Link>}>
      {dashboard.isLoading ? <LoadingRows count={5} /> : dashboard.isError ? <ErrorState retry={() => dashboard.refetch()} /> : dashboard.data?.activity?.length ? <div className="activity-list">{dashboard.data.activity.map((item, i) => <div className="activity-row" key={item.id} data-testid={`activity-${item.id}`}><span className={cn('activity-pin', `tone-${item.tone || 'blue'}`)}>{i === 0 ? <Zap size={13} /> : <Activity size={13} />}</span><div className="activity-copy"><strong>{item.label}</strong><span>{item.detail}</span></div><time>{prettyDate(item.createdAt)} · {prettyTime(item.createdAt)}</time></div>)}</div> : <EmptyState icon={Activity} title="No activity yet" detail="Operator actions and bot events will appear here." /> }
    </Card>
  </div>;
}

function StockBars({ stock }: { stock: StockSummary[] }) {
  if (!stock.length) return <EmptyState title="No milestones configured" detail="Add a milestone to start tracking inventory runway." action={<Link href="/rewards" className="btn btn-primary">Configure rewards</Link>} />;
  return <div className="stock-list">{stock.slice(0, 4).map(item => { const total = item.available + item.assigned + item.delivered + item.failed; const pct = total ? Math.round(item.available / total * 100) : 0; return <div className="stock-item" key={item.milestoneId}><div className="stock-label"><strong>{item.milestoneName}</strong><span><b>{number(item.available)}</b> available · {number(item.delivered)} delivered</span></div><div className="stock-track"><span style={{ width: `${Math.max(4, pct)}%` }} /></div><div className="stock-foot"><small>{pct}% runway remaining</small><Badge tone={pct < 20 ? 'amber' : 'green'}>{pct < 20 ? 'Watch' : 'Healthy'}</Badge></div></div>; })}</div>;
}

function RewardsPage() {
  const qc = useQueryClient(); const [filter, setFilter] = useState<'all' | 'available' | 'assigned' | 'delivered' | 'failed'>('all'); const [modal, setModal] = useState<'milestone' | 'reward' | null>(null); const [editingReward, setEditingReward] = useState<Reward | null>(null); const [editingMilestone, setEditingMilestone] = useState<Milestone | null>(null); const [confirmId, setConfirmId] = useState<number | null>(null);
  const milestones = useListMilestones(); const rewards = useListRewards(filter === 'all' ? undefined : { status: filter }); const stock = useGetRewardStock(); const deliveries = useListDeliveries();
  const delMilestone = useDeleteMilestone(); const delReward = useDeleteReward();
  const refresh = () => { qc.invalidateQueries({ queryKey: getListMilestonesQueryKey() }); qc.invalidateQueries({ queryKey: getListRewardsQueryKey() }); qc.invalidateQueries({ queryKey: getGetRewardStockQueryKey() }); qc.invalidateQueries({ queryKey: getListDeliveriesQueryKey() }); };
  return <div className="animate-rise"><div className="toolbar"><div className="filter-tabs">{(['all', 'available', 'assigned', 'delivered', 'failed'] as const).map(tab => <button key={tab} data-testid={`filter-rewards-${tab}`} className={cn('filter-tab', filter === tab && 'filter-tab-active')} onClick={() => setFilter(tab)}>{tab === 'all' ? 'All inventory' : tab}<span>{tab === 'all' ? rewards.data?.length ?? '—' : tab === 'available' ? stock.data?.reduce((a, s) => a + s.available, 0) ?? '—' : ''}</span></button>)}</div><Button onClick={() => { setEditingReward(null); setModal('reward'); }} data-testid="button-add-reward"><Plus size={16} /> Add reward</Button></div>
    <div className="rewards-layout"><div className="rewards-main"><Card title="Milestones" action={<Button variant="quiet" onClick={() => { setEditingMilestone(null); setModal('milestone'); }} data-testid="button-add-milestone"><Plus size={15} /> New milestone</Button>}>{milestones.isLoading ? <LoadingRows /> : milestones.isError ? <ErrorState retry={() => milestones.refetch()} /> : milestones.data?.length ? <div className="milestone-list">{milestones.data.map(m => <MilestoneRow key={m.id} item={m} onEdit={() => { setEditingMilestone(m); setModal('milestone'); }} onDelete={() => setConfirmId(m.id)} />)}</div> : <EmptyState icon={Gauge} title="Your reward ladder is empty" detail="Start with the first referral milestone and give people a reason to share." action={<Button onClick={() => setModal('milestone')}><Plus size={15} /> Add first milestone</Button>} />}</Card>
      <Card title="Delivery pulse" action={<span className="section-caption">{number(deliveries.data?.length)} recent deliveries</span>}>{deliveries.isLoading ? <LoadingRows count={3} /> : deliveries.isError ? <ErrorState retry={() => deliveries.refetch()} /> : <DeliveryList deliveries={deliveries.data || []} />}</Card></div>
      <Card title="Reward inventory" className="rewards-table-card" action={<span className="section-caption">Showing {number(rewards.data?.length)} records</span>}>{rewards.isLoading ? <LoadingRows count={6} /> : rewards.isError ? <ErrorState retry={() => rewards.refetch()} /> : rewards.data?.length ? <div className="table-wrap"><table><thead><tr><th>Reward</th><th>Milestone</th><th>Type</th><th>Status</th><th>Added</th><th /></tr></thead><tbody>{rewards.data.map(r => <tr key={r.id} data-testid={`row-reward-${r.id}`}><td><div className="table-primary"><span className="reward-symbol"><Code2 size={14} /></span><span><strong>{r.label}</strong><small>#{r.id} {r.payload ? `· ${r.payload.slice(0, 24)}` : ''}</small></span></div></td><td><span className="mono">#{r.milestoneId}</span></td><td><Badge tone="navy">{r.type}</Badge></td><td><Badge tone={r.status === 'available' ? 'green' : r.status === 'failed' ? 'red' : r.status === 'delivered' ? 'cyan' : 'amber'}>{r.status}</Badge></td><td className="muted-cell">{prettyDate(r.createdAt)}</td><td><div className="row-actions"><button className="icon-btn" aria-label={`Edit reward ${r.id}`} data-testid={`button-edit-reward-${r.id}`} onClick={() => { setEditingReward(r); setModal('reward'); }}><Pencil size={14} /></button>{r.status === 'available' && <button className="icon-btn danger-icon" aria-label={`Delete reward ${r.id}`} data-testid={`button-delete-reward-${r.id}`} onClick={() => setConfirmId(-r.id)}><Trash2 size={14} /></button>}</div></td></tr>)}</tbody></table></div> : <EmptyState icon={Archive} title="No rewards match this view" detail="Add stock or switch the inventory filter." action={<Button onClick={() => setModal('reward')}><Plus size={15} /> Add reward</Button>} />}</Card>
    </div>
    {modal === 'milestone' && <MilestoneForm value={editingMilestone} onClose={() => setModal(null)} onSaved={() => { refresh(); setModal(null); }} />}
    {modal === 'reward' && <RewardForm value={editingReward} milestones={milestones.data || []} onClose={() => setModal(null)} onSaved={() => { refresh(); setModal(null); }} />}
    {confirmId !== null && <ConfirmModal title={confirmId > 0 ? 'Delete milestone?' : 'Remove reward from inventory?'} detail="This cannot be undone. Only unclaimed inventory can be removed." onClose={() => setConfirmId(null)} onConfirm={() => { if (confirmId > 0) delMilestone.mutate({ id: confirmId }, { onSuccess: () => { refresh(); setConfirmId(null); } }); else delReward.mutate({ id: Math.abs(confirmId) }, { onSuccess: () => { refresh(); setConfirmId(null); } }); }} busy={delMilestone.isPending || delReward.isPending} />}
  </div>;
}

function MilestoneRow({ item, onEdit, onDelete }: { item: Milestone; onEdit: () => void; onDelete: () => void }) {
  const claimed = item.rewardCount ? Math.round(item.claimedCount / item.rewardCount * 100) : 0;
  return <div className="milestone-row"><div className="milestone-number">{item.referralTarget}</div><div className="milestone-info"><div><strong>{item.name}</strong><Badge tone={item.enabled ? 'green' : 'neutral'}>{item.enabled ? 'Active' : 'Paused'}</Badge></div><span>{number(item.rewardCount)} rewards stocked · {number(item.claimedCount)} claimed</span><div className="mini-track"><span style={{ width: `${Math.min(100, claimed)}%` }} /></div></div><div className="milestone-actions"><button className="icon-btn" aria-label={`Edit ${item.name}`} data-testid={`button-edit-milestone-${item.id}`} onClick={onEdit}><Pencil size={14} /></button><button className="icon-btn danger-icon" aria-label={`Delete ${item.name}`} data-testid={`button-delete-milestone-${item.id}`} onClick={onDelete}><Trash2 size={14} /></button></div></div>;
}

function DeliveryList({ deliveries }: { deliveries: Array<{ id: number; telegramUserId: number; status: string; createdAt: string }> }) {
  if (!deliveries.length) return <EmptyState icon={PackageCheck} title="No delivery history" detail="Completed reward sends will show up here." />;
  return <div className="delivery-list">{deliveries.slice(0, 4).map(d => <div className="delivery-row" key={d.id}><span className={cn('delivery-icon', d.status === 'delivered' ? 'delivery-ok' : d.status === 'failed' ? 'delivery-fail' : 'delivery-wait')}>{d.status === 'delivered' ? <Check size={14} /> : d.status === 'failed' ? <X size={14} /> : <Clock3 size={14} />}</span><div><strong>Reward #{d.id} → {d.telegramUserId}</strong><small>{prettyDate(d.createdAt)} · {prettyTime(d.createdAt)}</small></div><Badge tone={d.status === 'delivered' ? 'green' : d.status === 'failed' ? 'red' : 'amber'}>{d.status}</Badge></div>)}</div>;
}

function MilestoneForm({ value, onClose, onSaved }: { value: Milestone | null; onClose: () => void; onSaved: () => void }) {
  const create = useCreateMilestone(); const update = useUpdateMilestone(); const [name, setName] = useState(value?.name || ''); const [target, setTarget] = useState(String(value?.referralTarget || 5)); const [enabled, setEnabled] = useState(value?.enabled ?? true);
  const submit = () => { const data = { name: name.trim(), referralTarget: Number(target), enabled }; if (!data.name || !data.referralTarget) return; if (value) update.mutate({ id: value.id, data }, { onSuccess: onSaved }); else create.mutate({ data }, { onSuccess: onSaved }); };
  return <Modal title={value ? 'Edit milestone' : 'New milestone'} onClose={onClose}><div className="form-grid"><label>Milestone name<input data-testid="input-milestone-name" value={name} onChange={e => setName(e.target.value)} placeholder="Founding circle" /></label><label>Referral target<input data-testid="input-milestone-target" type="number" min="1" value={target} onChange={e => setTarget(e.target.value)} /></label></div><div className="setting-line"><div><strong>Available to members</strong><span>Let the bot award this milestone.</span></div><Toggle checked={enabled} onChange={setEnabled} label="milestone enabled" /></div><div className="modal-actions"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button onClick={submit} disabled={create.isPending || update.isPending}>{create.isPending || update.isPending ? 'Saving…' : 'Save milestone'}</Button></div></Modal>;
}

function RewardForm({ value, milestones, onClose, onSaved }: { value: Reward | null; milestones: Milestone[]; onClose: () => void; onSaved: () => void }) {
  const create = useCreateReward(); const update = useUpdateReward(); const [milestoneId, setMilestoneId] = useState(String(value?.milestoneId || milestones[0]?.id || '')); const [type, setType] = useState<Reward['type']>(value?.type || 'code'); const [label, setLabel] = useState(value?.label || ''); const [payload, setPayload] = useState(value?.payload || '');
  const submit = () => { if (!label.trim() || !milestoneId) return; if (value) update.mutate({ id: value.id, data: { label: label.trim(), payload } }, { onSuccess: onSaved }); else create.mutate({ data: { milestoneId: Number(milestoneId), type: type as Reward['type'], label: label.trim(), payload, enabled: true } }, { onSuccess: onSaved }); };
  return <Modal title={value ? 'Edit reward' : 'Add reward'} onClose={onClose}><div className="form-grid"><label>Milestone<select data-testid="select-reward-milestone" value={milestoneId} onChange={e => setMilestoneId(e.target.value)}>{milestones.map(m => <option key={m.id} value={m.id}>{m.name} · {m.referralTarget} referrals</option>)}</select></label><label>Reward type<select data-testid="select-reward-type" value={type} onChange={e => setType(e.target.value as Reward['type'])} disabled={!!value}>{['text', 'link', 'code', 'json', 'file', 'photo', 'video', 'animation', 'document', 'apk', 'media'].map(t => <option key={t} value={t}>{t}</option>)}</select></label></div><label>Label<input data-testid="input-reward-label" value={label} onChange={e => setLabel(e.target.value)} placeholder="Premium access code" /></label><label>Payload<textarea data-testid="input-reward-payload" value={payload} onChange={e => setPayload(e.target.value)} placeholder="Paste the code, link, or message payload" rows={4} /></label><div className="modal-actions"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button onClick={submit} disabled={create.isPending || update.isPending}>{create.isPending || update.isPending ? 'Saving…' : 'Save reward'}</Button></div></Modal>;
}

function UsersPage() {
  const [search, setSearch] = useState(''); const [active, setActive] = useState<number | null>(null); const params = useMemo(() => search.trim() ? { search: search.trim(), limit: 50 } : { limit: 50 }, [search]); const users = useListUsers(params); const profile = useGetUser(active || 0, { query: { enabled: !!active, queryKey: getGetUserQueryKey(active || 0) } });
  return <div className="animate-rise"><Card className="users-card"><div className="user-toolbar"><div className="search-field"><Search size={17} /><input data-testid="input-search-users" type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search username or Telegram ID" /><kbd>⌘ K</kbd></div><span className="section-caption">{number(users.data?.length)} members in view</span></div>{users.isLoading ? <LoadingRows count={6} /> : users.isError ? <ErrorState retry={() => users.refetch()} /> : users.data?.length ? <div className="table-wrap"><table><thead><tr><th>Member</th><th>Referral status</th><th>Referrals</th><th>Points</th><th>Joined</th><th>Status</th><th /></tr></thead><tbody>{users.data.map(u => <tr key={u.telegramId} data-testid={`row-user-${u.telegramId}`} onClick={() => setActive(u.telegramId)} className="clickable-row"><td><div className="table-primary"><span className="user-avatar">{initials(u.username)}</span><span><strong>{u.username || 'Unnamed member'}</strong><small className="mono">{u.telegramId}</small></span></div></td><td><Badge tone={u.referralStatus === 'completed' ? 'green' : 'amber'}>{u.referralStatus.replaceAll('_', ' ')}</Badge></td><td className="mono">{u.referralCount}</td><td className="mono">{number(u.points)}</td><td className="muted-cell">{prettyDate(u.joinDate)}</td><td>{u.banned ? <Badge tone="red">Banned</Badge> : <Badge tone="green">Active</Badge>}</td><td><ChevronRight size={16} className="muted-cell" /></td></tr>)}</tbody></table></div> : <EmptyState icon={UserRound} title="No members found" detail={search ? 'Try a different handle or Telegram ID.' : 'Members will appear after the bot receives its first start.'} />}</Card>{active && <UserDrawer profile={profile.data} loading={profile.isLoading} error={profile.isError} onClose={() => setActive(null)} />}</div>;
}

function UserDrawer({ profile, loading, error, onClose }: { profile?: { user: User; referralHistory: Array<{ id: number; referredTelegramId: number; status: string; createdAt: string }>; rewardHistory: Array<{ id: number; milestoneId: number; status: string; createdAt: string }> }; loading: boolean; error: boolean; onClose: () => void }) {
  const qc = useQueryClient(); const action = useApplyUserAction(); const [actionType, setActionType] = useState('add_referrals'); const [amount, setAmount] = useState('1'); const [reason, setReason] = useState(''); const u = profile?.user;
  const run = () => { if (!u) return; action.mutate({ telegramId: u.telegramId, data: { action: actionType as 'ban', amount: ['add_referrals', 'remove_referrals', 'add_points', 'remove_points'].includes(actionType) ? Number(amount) : undefined, reason } }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getGetUserQueryKey(u.telegramId) }); qc.invalidateQueries({ queryKey: getListUsersQueryKey() }); qc.invalidateQueries({ queryKey: getListAuditLogsQueryKey() }); } }); };
  return <div className="drawer-backdrop"><aside className="user-drawer"><div className="drawer-head"><div><div className="eyebrow">Member profile</div><h2>{loading ? 'Loading member…' : u?.username || 'Member detail'}</h2></div><button className="icon-btn" aria-label="Close member detail" data-testid="button-close-user-drawer" onClick={onClose}><X size={18} /></button></div>{error ? <ErrorState /> : loading ? <LoadingRows count={7} /> : u ? <><div className="profile-hero"><span className="profile-avatar">{initials(u.username)}</span><div><strong>{u.username || 'Unnamed member'}</strong><span className="mono">{u.telegramId}</span></div><Badge tone={u.banned ? 'red' : 'green'}>{u.banned ? 'Banned' : 'Active'}</Badge></div><div className="profile-stats"><div><span>Referrals</span><strong>{u.referralCount}</strong></div><div><span>Points</span><strong>{number(u.points)}</strong></div><div><span>Joined</span><strong>{prettyDate(u.joinDate)}</strong></div></div><div className="drawer-section"><div className="drawer-section-head"><h3>Quick action</h3><span>Logged to audit</span></div><div className="form-grid"><select data-testid="select-user-action" value={actionType} onChange={e => setActionType(e.target.value)}>{['add_referrals', 'remove_referrals', 'add_points', 'remove_points', 'reset_progress', 'ban', 'unban'].map(a => <option key={a} value={a}>{a.replaceAll('_', ' ')}</option>)}</select>{['add_referrals', 'remove_referrals', 'add_points', 'remove_points'].includes(actionType) && <input data-testid="input-user-action-amount" type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)} />}</div><input data-testid="input-user-action-reason" value={reason} onChange={e => setReason(e.target.value)} placeholder="Reason (optional)" /><Button onClick={run} disabled={action.isPending} className="w-full">{action.isPending ? 'Applying…' : 'Apply action'}</Button></div><div className="drawer-section"><div className="drawer-section-head"><h3>Referral history</h3><span>{profile?.referralHistory.length || 0} records</span></div>{profile?.referralHistory.length ? profile.referralHistory.slice(0, 4).map(r => <div className="history-row" key={r.id}><span className="history-dot" /><div><strong>Referred member {r.referredTelegramId}</strong><small>{prettyDate(r.createdAt)}</small></div><Badge tone={r.status === 'completed' ? 'green' : 'amber'}>{r.status.replaceAll('_', ' ')}</Badge></div>) : <p className="muted-copy">No referral activity recorded.</p>}</div></> : null}</aside></div>;
}

function ChannelsPage() {
  const qc = useQueryClient(); const channels = useListChannels(); const create = useCreateChannel(); const update = useUpdateChannel(); const remove = useDeleteChannel(); const [editing, setEditing] = useState<ForceChannel | null>(null); const [open, setOpen] = useState(false); const [confirm, setConfirm] = useState<number | null>(null);
  const refresh = () => qc.invalidateQueries({ queryKey: getListChannelsQueryKey() });
  return <div className="animate-rise"><Card title="Entry requirements" action={<Button onClick={() => { setEditing(null); setOpen(true); }} data-testid="button-add-channel"><Plus size={16} /> Add channel</Button>}>{channels.isLoading ? <LoadingRows count={3} /> : channels.isError ? <ErrorState retry={() => channels.refetch()} /> : channels.data?.length ? <div className="channel-list">{channels.data.map(c => <div className="channel-row" key={c.id} data-testid={`row-channel-${c.id}`}><div className="channel-icon"><Radio size={17} /></div><div className="channel-main"><div><strong>{c.title}</strong><Badge tone={c.enabled ? 'green' : 'neutral'}>{c.enabled ? 'Required' : 'Paused'}</Badge></div><span className="mono">{c.chatId}</span><a href={c.inviteLink} target="_blank" rel="noreferrer" className="text-link">{c.inviteLink} <ArrowUpRight size={13} /></a></div><div className="channel-members"><strong>{number(c.memberCount)}</strong><span>members</span></div><Toggle checked={c.enabled} onChange={enabled => update.mutate({ id: c.id, data: { enabled } }, { onSuccess: refresh })} label={`channel ${c.id} enabled`} /><div className="row-actions"><button className="icon-btn" aria-label={`Edit channel ${c.id}`} data-testid={`button-edit-channel-${c.id}`} onClick={() => { setEditing(c); setOpen(true); }}><Pencil size={14} /></button><button className="icon-btn danger-icon" aria-label={`Delete channel ${c.id}`} data-testid={`button-delete-channel-${c.id}`} onClick={() => setConfirm(c.id)}><Trash2 size={14} /></button></div></div>)}</div> : <EmptyState icon={Radio} title="No required channels" detail="Add the channels members should join before they can collect rewards." action={<Button onClick={() => setOpen(true)}><Plus size={15} /> Add channel</Button>} />}</Card><div className="info-banner"><CircleHelp size={17} /><div><strong>Keep the entry path intentional</strong><p>Channels are checked in order. Use sort order to put your primary community first.</p></div></div>{open && <ChannelForm value={editing} onClose={() => setOpen(false)} onSaved={() => { refresh(); setOpen(false); }} />}{confirm && <ConfirmModal title="Remove this channel?" detail="Members will no longer be prompted to join it." onClose={() => setConfirm(null)} onConfirm={() => remove.mutate({ id: confirm }, { onSuccess: () => { refresh(); setConfirm(null); } })} busy={remove.isPending} />}</div>;
}

function ChannelForm({ value, onClose, onSaved }: { value: ForceChannel | null; onClose: () => void; onSaved: () => void }) {
  const create = useCreateChannel(); const update = useUpdateChannel(); const [title, setTitle] = useState(value?.title || ''); const [chatId, setChatId] = useState(value?.chatId || ''); const [inviteLink, setInviteLink] = useState(value?.inviteLink || ''); const [enabled, setEnabled] = useState(value?.enabled ?? true); const [sortOrder, setSortOrder] = useState(String(value?.sortOrder || 1));
  const submit = () => { const data = { title: title.trim(), chatId: chatId.trim(), inviteLink: inviteLink.trim(), enabled, sortOrder: Number(sortOrder) }; if (!title || !chatId || !inviteLink) return; if (value) update.mutate({ id: value.id, data }, { onSuccess: onSaved }); else create.mutate({ data }, { onSuccess: onSaved }); };
  return <Modal title={value ? 'Edit channel' : 'Add channel'} onClose={onClose}><label>Channel title<input data-testid="input-channel-title" value={title} onChange={e => setTitle(e.target.value)} placeholder="Relayroom Community" /></label><div className="form-grid"><label>Chat ID<input data-testid="input-channel-chat-id" value={chatId} onChange={e => setChatId(e.target.value)} placeholder="-100…" /></label><label>Sort order<input data-testid="input-channel-sort-order" type="number" min="1" value={sortOrder} onChange={e => setSortOrder(e.target.value)} /></label></div><label>Invite link<input data-testid="input-channel-link" value={inviteLink} onChange={e => setInviteLink(e.target.value)} placeholder="https://t.me/…" /></label><div className="setting-line"><div><strong>Require membership</strong><span>Members must join this channel to continue.</span></div><Toggle checked={enabled} onChange={setEnabled} label="channel required" /></div><div className="modal-actions"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button onClick={submit} disabled={create.isPending || update.isPending}>{create.isPending || update.isPending ? 'Saving…' : 'Save channel'}</Button></div></Modal>;
}

function ContentPage() {
  const qc = useQueryClient(); const query = useGetContent(); const update = useUpdateContent(); const [draft, setDraft] = useState<BotContent | null>(null); const content = draft || query.data; const set = (key: keyof BotContent, value: string) => setDraft({ ...(content as BotContent), [key]: value }); const save = () => content && update.mutate({ data: content }, { onSuccess: result => { setDraft(result); qc.invalidateQueries({ queryKey: getGetContentQueryKey() }); } });
  const fields: Array<[keyof BotContent, string, string]> = [['welcomeMessage', 'Welcome message', 'Shown when someone first starts the bot.'], ['howItWorksMessage', 'How it works', 'Set expectations before the first referral.'], ['forceSubscribeMessage', 'Force-subscribe message', 'Explains why a member needs to join channels.'], ['rewardMessage', 'Reward message', 'Shown when a reward is ready.'], ['successMessage', 'Success message', 'Confirmation after a successful claim.'], ['errorMessage', 'Error message', 'Fallback when an action cannot complete.'], ['maintenanceMessage', 'Maintenance message', 'Shown while maintenance mode is on.'], ['disclaimer', 'Disclaimer', 'The acknowledgement members accept.'], ['supportMessage', 'Support message', 'Help text for members who need a hand.']];
  return <div className="animate-rise">{query.isLoading ? <Card><LoadingRows count={6} /></Card> : query.isError ? <Card><ErrorState retry={() => query.refetch()} /></Card> : <><div className="content-layout"><Card title="Message library"><div className="content-index">{fields.map(([key, label]) => <a href={`#${key}`} key={key} className={cn(content?.[key] ? '' : 'content-index-muted')}><span>{label}</span><ChevronRight size={14} /></a>)}</div></Card><div className="content-editor"><Card title="Bot copy" action={<Button onClick={save} disabled={update.isPending} data-testid="button-save-content"><Check size={15} /> {update.isPending ? 'Saving…' : 'Save changes'}</Button>}><div className="copy-fields">{fields.map(([key, label, hint]) => <label id={key} key={key}>{label}<span className="field-hint">{hint}</span><textarea data-testid={`input-content-${key}`} value={content?.[key] || ''} onChange={e => set(key, e.target.value)} rows={key === 'disclaimer' ? 5 : 3} /></label>)}</div></Card></div></div><div className="info-banner"><FileText size={17} /><div><strong>Keep copy concise</strong><p>Telegram members skim. Put the action first, then the reason.</p></div></div></>}</div>;
}

function BroadcastsPage() {
  const qc = useQueryClient(); const list = useListBroadcasts(); const create = useCreateBroadcast(); const [open, setOpen] = useState(false);
  return <div className="animate-rise"><div className="toolbar"><div className="toolbar-note"><Megaphone size={17} /><span>Announce once, deliver with confidence.</span></div><Button onClick={() => setOpen(true)} data-testid="button-new-broadcast"><Plus size={16} /> New broadcast</Button></div><Card title="Broadcast queue" action={<span className="section-caption">{number(list.data?.length)} broadcasts</span>}>{list.isLoading ? <LoadingRows count={5} /> : list.isError ? <ErrorState retry={() => list.refetch()} /> : list.data?.length ? <div className="broadcast-list">{list.data.map(b => <BroadcastRow item={b} key={b.id} />)}</div> : <EmptyState icon={Megaphone} title="The queue is quiet" detail="Create a broadcast when your community needs to hear from you." action={<Button onClick={() => setOpen(true)}><Plus size={15} /> Compose broadcast</Button>} />}</Card>{open && <BroadcastForm onClose={() => setOpen(false)} onSaved={() => { qc.invalidateQueries({ queryKey: getListBroadcastsQueryKey() }); setOpen(false); }} />}</div>;
}

function BroadcastRow({ item }: { item: Broadcast }) {
  const pct = item.totalRecipients ? Math.round(item.sentCount / item.totalRecipients * 100) : 0; return <div className="broadcast-row" data-testid={`row-broadcast-${item.id}`}><div className="broadcast-type"><Megaphone size={16} /></div><div className="broadcast-copy"><div><strong>{item.content.slice(0, 80) || 'Untitled broadcast'}</strong><Badge tone={item.status === 'completed' ? 'green' : item.status === 'failed' ? 'red' : item.status === 'processing' ? 'cyan' : 'amber'}>{item.status}</Badge></div><span>{item.contentType} · created {prettyDate(item.createdAt)}</span><div className="broadcast-progress"><span style={{ width: `${pct}%` }} /></div></div><div className="broadcast-numbers"><strong>{number(item.sentCount)}<small> / {number(item.totalRecipients)}</small></strong><span>sent · {number(item.failedCount)} failed</span></div><ChevronRight size={16} className="muted-cell" /></div>;
}

function BroadcastForm({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const create = useCreateBroadcast(); const [type, setType] = useState('text'); const [content, setContent] = useState(''); const [buttonText, setButtonText] = useState(''); const [buttonUrl, setButtonUrl] = useState(''); const [preview, setPreview] = useState(true);
  const submit = () => { if (!content.trim()) return; create.mutate({ data: { contentType: type as 'text', content: content.trim(), buttonText: buttonText || undefined, buttonUrl: buttonUrl || undefined, preview } }, { onSuccess: onSaved }); };
  return <Modal title="New broadcast" onClose={onClose}><div className="form-grid"><label>Format<select data-testid="select-broadcast-type" value={type} onChange={e => setType(e.target.value)}>{['text', 'photo', 'video', 'animation', 'document'].map(t => <option key={t} value={t}>{t}</option>)}</select></label><label>Audience<span className="input-static">All active members</span></label></div><label>Message<textarea data-testid="input-broadcast-content" value={content} onChange={e => setContent(e.target.value)} rows={6} placeholder="Write a clear update for your members…" /></label><div className="form-grid"><label>Button label<input data-testid="input-broadcast-button-text" value={buttonText} onChange={e => setButtonText(e.target.value)} placeholder="Open community" /></label><label>Button URL<input data-testid="input-broadcast-button-url" value={buttonUrl} onChange={e => setButtonUrl(e.target.value)} placeholder="https://t.me/…" /></label></div><div className="setting-line"><div><strong>Show link preview</strong><span>Let Telegram render a preview when available.</span></div><Toggle checked={preview} onChange={setPreview} label="broadcast preview" /></div><div className="modal-actions"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button onClick={submit} disabled={create.isPending}><Send size={15} /> {create.isPending ? 'Queueing…' : 'Queue broadcast'}</Button></div></Modal>;
}

function AuditPage() {
  const logs = useListAuditLogs(); return <div className="animate-rise"><div className="audit-summary"><div><ShieldCheck size={18} /><span>Immutable operator record</span></div><span className="mono">{number(logs.data?.length)} events loaded</span></div><Card title="Operator activity" action={<Button variant="quiet" onClick={() => logs.refetch()}><RefreshCw size={15} /> Refresh</Button>}>{logs.isLoading ? <LoadingRows count={7} /> : logs.isError ? <ErrorState retry={() => logs.refetch()} /> : logs.data?.length ? <div className="audit-list">{logs.data.map(log => <div className="audit-row" key={log.id} data-testid={`row-audit-${log.id}`}><span className="audit-marker"><ClipboardList size={14} /></span><div className="audit-copy"><strong>{log.action}</strong><span>{log.detail || 'No additional detail'}{log.targetTelegramId ? ` · target ${log.targetTelegramId}` : ''}</span></div><div className="audit-actor"><span className="mono">{log.actorTelegramId}</span><small>{prettyDate(log.createdAt)} · {prettyTime(log.createdAt)}</small></div></div>)}</div> : <EmptyState icon={ClipboardList} title="No audit events" detail="The first operator action will create a record here." />}</Card></div>;
}

function SettingsPage() {
  const qc = useQueryClient(); const query = useGetSettings(); const update = useUpdateSettings(); const [draft, setDraft] = useState<BotSettings | null>(null); const s = draft || query.data; const patch = (data: Partial<BotSettings>) => setDraft({ ...(s as BotSettings), ...data }); const save = () => s && update.mutate({ data: { maintenanceMode: s.maintenanceMode, maintenanceMessage: s.maintenanceMessage, referralSystemEnabled: s.referralSystemEnabled, disclaimerEnabled: s.disclaimerEnabled, supportBotLink: s.supportBotLink, supportButtonLabel: s.supportButtonLabel } }, { onSuccess: result => { setDraft(result); qc.invalidateQueries({ queryKey: getGetSettingsQueryKey() }); } });
  return <div className="animate-rise settings-layout">{query.isLoading ? <Card><LoadingRows count={5} /></Card> : query.isError ? <Card><ErrorState retry={() => query.refetch()} /></Card> : s ? <><div className="settings-main"><Card title="System posture" action={<Button onClick={save} disabled={update.isPending} data-testid="button-save-settings"><Check size={15} /> {update.isPending ? 'Saving…' : 'Save settings'}</Button>}><div className={cn('maintenance-card', s.maintenanceMode && 'maintenance-on')}><div className="maintenance-icon"><HeartPulse size={19} /></div><div><strong>{s.maintenanceMode ? 'Maintenance mode is on' : 'Bot is open to members'}</strong><p>{s.maintenanceMode ? 'New member actions are paused.' : 'Referral and reward actions are available now.'}</p></div><Toggle checked={s.maintenanceMode} onChange={maintenanceMode => patch({ maintenanceMode })} label="maintenance mode" /></div><div className="settings-list"><SettingRow icon={Zap} title="Referral system" detail="Allow members to earn rewards through referrals." checked={s.referralSystemEnabled} onChange={referralSystemEnabled => patch({ referralSystemEnabled })} /><SettingRow icon={FileText} title="Disclaimer acknowledgement" detail="Ask members to accept the disclaimer before continuing." checked={s.disclaimerEnabled} onChange={disclaimerEnabled => patch({ disclaimerEnabled })} /></div><label>Maintenance message<span className="field-hint">Shown while the bot is paused.</span><textarea data-testid="input-maintenance-message" value={s.maintenanceMessage || ''} onChange={e => patch({ maintenanceMessage: e.target.value })} rows={3} /></label></Card><Card title="Support handoff"><div className="form-grid"><label>Support button label<input data-testid="input-support-label" value={s.supportButtonLabel} onChange={e => patch({ supportButtonLabel: e.target.value })} /></label><label>Support bot link<input data-testid="input-support-link" value={s.supportBotLink} onChange={e => patch({ supportBotLink: e.target.value })} /></label></div></Card></div><div className="settings-side"><Card title="Workspace identity"><div className="identity-block"><span className="identity-mark"><Bot size={23} /></span><div><strong>{s.botUsername ? `@${s.botUsername.replace('@', '')}` : 'Relayroom Bot'}</strong><span>Telegram bot</span></div></div><div className="identity-meta"><span>Owner Telegram ID</span><strong className="mono">{s.ownerTelegramId}</strong></div></Card><Card title="System notes"><div className="notes-list"><div><Database size={15} /><span>Settings are stored server-side.</span></div><div><ShieldCheck size={15} /><span>Every change is added to the audit log.</span></div><div><RotateCcw size={15} /><span>Changes are live immediately.</span></div></div></Card></div></> : null}</div>;
}

function SettingRow({ icon: Icon, title, detail, checked, onChange }: { icon: typeof Zap; title: string; detail: string; checked: boolean; onChange: (v: boolean) => void }) { return <div className="setting-row"><div className="setting-row-icon"><Icon size={17} /></div><div className="setting-row-copy"><strong>{title}</strong><span>{detail}</span></div><Toggle checked={checked} onChange={onChange} label={title} /></div>; }

function ConfirmModal({ title, detail, onClose, onConfirm, busy }: { title: string; detail: string; onClose: () => void; onConfirm: () => void; busy?: boolean }) { return <Modal title={title} onClose={onClose}><div className="confirm-copy"><div className="confirm-icon"><Trash2 size={19} /></div><p>{detail}</p></div><div className="modal-actions"><Button variant="quiet" onClick={onClose}>Keep it</Button><Button variant="danger" onClick={onConfirm} disabled={busy}>{busy ? 'Removing…' : 'Confirm removal'}</Button></div></Modal>; }

function Router() { return <Shell><Switch><Route path="/" component={DashboardPage} /><Route path="/rewards" component={RewardsPage} /><Route path="/users" component={UsersPage} /><Route path="/channels" component={ChannelsPage} /><Route path="/content" component={ContentPage} /><Route path="/broadcasts" component={BroadcastsPage} /><Route path="/audit" component={AuditPage} /><Route path="/settings" component={SettingsPage} /><Route component={NotFound} /></Switch></Shell>; }

function RoutedErrorBoundary({ children }: { children: ReactNode }) { const [location] = useLocation(); return <ErrorBoundary resetKey={location}>{children}</ErrorBoundary>; }
function App() { return <QueryClientProvider client={queryClient}><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><RoutedErrorBoundary><Router /></RoutedErrorBoundary></WouterRouter></QueryClientProvider>; }
export default App;